---
abstract: 'Ext.Direct client in Perl'
author:
  - 'Alexander Tokarev <tokarev@cpan.org>'
build_requires:
  RPC::ExtDirect::Server: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RPC-ExtDirect-Client
no_index:
  directory:
    - t
    - inc
requires:
  HTTP::Tiny: 0.014
  JSON: 2.0
resources:
  bugtracker: http://github.com/nohuhu/RPC-ExtDirect-Client/issues
  repository: http://github.com/nohuhu/RPC-ExtDirect-Client
version: 0.2
